from dataclasses import dataclass


@dataclass
class EmbeddedChunk:

    chunk_id: str           #A unique identifier for the chunk, which is a string that combines the PMCID, section title, and chunk index. This allows us to easily identify and retrieve specific chunks of text from the database.

    embedding: list[float]  #The embedding of the chunk, which is a list of floating-point numbers that represents the semantic meaning of the chunk. This can be used to compare the similarity of chunks and retrieve relevant chunks based on a query.

    embedding_model: str    #The name of the embedding model used to generate the embedding, which is a string that represents the specific model or algorithm used to create the embedding. This can be useful for tracking which model was used for each chunk and for ensuring consistency when comparing embeddings generated by different models.

    embedding_version: int  #The version of the embedding model used to generate the embedding, which is an integer that represents the specific version or iteration of the embedding model. This can be useful for tracking changes and improvements in the embedding model over time, and for ensuring that embeddings generated with different versions of the model are not compared directly without proper consideration of potential differences in their representations.

    metadata: dict          #A dictionary that contains additional metadata about the chunk, such as the PMCID of the paper from which the chunk was extracted, the section title, the chunk index, and any other relevant information. This can be used to provide context for the chunk and to facilitate retrieval of related chunks based on shared metadata attributes.